version: "3.5"
services:
  mysqldevelop:
    image: mysql:5.7.35
    container_name: mysqldevelop
    environment:
      - MYSQL_ROOT_PASSWORD=200247
        # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=''
    ports: 
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      default:
        ipv4_address: 10.0.5.2
networks:
  default:
    external: true
    name: netdevelop
 